FROM python:3.9

# Install python requirements
RUN pip install --no-cache-dir \
        flake8 \
        pylint \
        pydocstyle \
        mypy \
        nbqa \
        # IPython and its extensions
        jupyter \
        pycodestyle_magic \
        mypy-ipython
